# Generated by Django 3.0.2 on 2020-01-16 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200116_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 13, 54, 58, 60229), verbose_name='date published'),
        ),
    ]
