# Generated by Django 3.0.2 on 2020-01-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorial',
            old_name='publushed',
            new_name='published',
        ),
    ]
