# Generated by Django 3.0.2 on 2020-01-16 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='category_slug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='category_summary',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 13, 27, 6, 613261), verbose_name='date published'),
        ),
    ]
