# Generated by Django 3.0.2 on 2020-01-11 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200111_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 14, 1, 5, 91492), verbose_name='date published'),
        ),
    ]
