# Generated by Django 3.0.2 on 2020-01-17 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200116_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 19, 37, 39, 220683), verbose_name='date published'),
        ),
    ]
