# Generated by Django 3.0.2 on 2020-01-12 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200111_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 22, 28, 53, 122828), verbose_name='date published'),
        ),
    ]
